DevOps/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Both</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>Service Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOps/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Annuity_Manual_Remove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Annuity Manual Remove</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Life_Manual_Remove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Life Manual Remove</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOps/src/classes/Check_for_Ann_Life_Manual_Remove_Handler.cls
public class Check_for_Ann_Life_Manual_Remove_Handler {
    
    public static void afterInsertorUpdate(List<Account> account){
        // Account acc=new Account();
        List<Contact> con = new List<Contact>();
        List<Contact> Updatecon = new List<Contact>();
        Set<Id> AccntIds = new Set<Id>();
        for(Account accnt: account)
        {
            AccntIds.add(accnt.Id);
        }
        con = [select Id,Annuity_Manual_Remove__c,Life_Manual_Remove__c from Contact where AccountId =: AccntIds];
        for(Account acc : account)
        {
            for(Contact cont: con)
            {
                if(acc.Line_of_Business__c=='Annuity')
                {
                    cont.Annuity_Manual_Remove__c=false;
                    cont.Life_Manual_Remove__c=true;
                }
                else if(acc.Line_of_Business__c=='Life'){
                    cont.Annuity_Manual_Remove__c=true;
                    cont.Life_Manual_Remove__c=false;
                } 
                else if(acc.Line_of_Business__c=='Both'){
                    cont.Annuity_Manual_Remove__c=false;
                    cont.Life_Manual_Remove__c=false;
                }
                Updatecon.add(cont);
            }
            update Updatecon;
        }
    }
    
}